# Generated by Django 4.2.17 on 2026-07-01 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_upload", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_sessions",
                        to="data_upload.dataupload",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WellTrendAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("well_id", models.CharField(max_length=255)),
                (
                    "bsw_trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("increasing", "Increasing"),
                            ("decreasing", "Decreasing"),
                            ("no_trend", "No Trend"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("bsw_slope", models.FloatField(blank=True, null=True)),
                (
                    "bsw_magnitude",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slightly", "Slightly"),
                            ("moderately", "Moderately"),
                            ("aggressively", "Aggressively"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "oil_rate_trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("increasing", "Increasing"),
                            ("decreasing", "Decreasing"),
                            ("no_trend", "No Trend"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("oil_rate_slope", models.FloatField(blank=True, null=True)),
                (
                    "oil_rate_magnitude",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slightly", "Slightly"),
                            ("moderately", "Moderately"),
                            ("aggressively", "Aggressively"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "glr_trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("increasing", "Increasing"),
                            ("decreasing", "Decreasing"),
                            ("no_trend", "No Trend"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("glr_slope", models.FloatField(blank=True, null=True)),
                (
                    "glr_magnitude",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slightly", "Slightly"),
                            ("moderately", "Moderately"),
                            ("aggressively", "Aggressively"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tubing_pressure_trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("increasing", "Increasing"),
                            ("decreasing", "Decreasing"),
                            ("no_trend", "No Trend"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("tubing_pressure_slope", models.FloatField(blank=True, null=True)),
                (
                    "tubing_pressure_magnitude",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slightly", "Slightly"),
                            ("moderately", "Moderately"),
                            ("aggressively", "Aggressively"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("bsw_flag", models.BooleanField(default=False)),
                ("oil_rate_flag", models.BooleanField(default=False)),
                ("glr_flag", models.BooleanField(default=False)),
                ("candidate_score", models.FloatField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("summary_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="well_trends",
                        to="analysis.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["-candidate_score"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bsw_weight", models.FloatField(default=100)),
                ("oil_rate_weight", models.FloatField(default=100)),
                ("glr_weight", models.FloatField(default=100)),
                ("tubing_pressure_weight", models.FloatField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="analysis.analysissession",
                    ),
                ),
            ],
        ),
    ]
