# Generated by Django 6.0.7 on 2026-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="welltrendanalysis",
            name="flow_line_pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="prod_method",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="test_status",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="well_choke_size",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
