# Generated by Django 4.2.7 on 2026-07-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_welltrendanalysis_flow_line_pressure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisweights",
            name="economic_limit_oil_bopd",
            field=models.FloatField(
                default=50, help_text="Economic oil rate limit (bopd)"
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="corrected_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Corrected values after normalization",
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="data_quality_score",
            field=models.FloatField(
                default=100.0, help_text="Percentage of valid data points"
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="is_choke_normalized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="original_values",
            field=models.JSONField(
                blank=True, default=dict, help_text="Original pre-normalization values"
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="outlier_count",
            field=models.IntegerField(
                default=0, help_text="Number of outlier points removed"
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="rejected_indices",
            field=models.JSONField(
                blank=True, default=list, help_text="Indices of rejected outlier points"
            ),
        ),
    ]
