# Generated by Django 4.2.7 on 2026-07-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_analysisweights_economic_limit_oil_bopd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="welltrendanalysis",
            name="actual_glr",
            field=models.FloatField(
                blank=True, help_text="Actual average GLR (scf/bbl)", null=True
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="actual_velocity",
            field=models.FloatField(
                blank=True, help_text="Actual gas velocity (ft/s)", null=True
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="completion_feasibility",
            field=models.CharField(
                choices=[
                    ("feasible", "Feasible"),
                    ("requires_deepening", "Requires Tubing Deepening"),
                    ("pressure_limited", "Insufficient Injection Pressure"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="critical_glr",
            field=models.FloatField(
                blank=True,
                help_text="Critical GLR for liquid loading (scf/bbl)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="critical_velocity",
            field=models.FloatField(
                blank=True, help_text="Critical gas velocity (ft/s)", null=True
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="days_to_economic_limit",
            field=models.IntegerField(
                blank=True, help_text="Days until economic limit reached", null=True
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="flowing_bhp",
            field=models.FloatField(
                blank=True, help_text="Flowing bottom-hole pressure (psi)", null=True
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="gas_utilization_efficiency",
            field=models.FloatField(
                blank=True, help_text="Gas utilization efficiency (0-100)", null=True
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="liquid_loading_flag",
            field=models.BooleanField(
                default=False, help_text="True if well is liquid-loaded"
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="pi_slope",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="pi_trend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("increasing", "Increasing"),
                    ("decreasing", "Decreasing"),
                    ("no_trend", "No Trend"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="productivity_index",
            field=models.FloatField(
                blank=True, help_text="Productivity Index (bopd/psi)", null=True
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="projected_oil_rate_6mo",
            field=models.FloatField(
                blank=True, help_text="Projected oil rate in 6 months (bopd)", null=True
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="recommended_gas_mmscf",
            field=models.FloatField(
                blank=True, help_text="Recommended gas injection (MMscf/d)", null=True
            ),
        ),
        migrations.AddField(
            model_name="welltrendanalysis",
            name="static_reservoir_pressure",
            field=models.FloatField(
                blank=True, help_text="Static reservoir pressure (psi)", null=True
            ),
        ),
        migrations.CreateModel(
            name="PVTProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_gravity",
                    models.FloatField(
                        default=35.0, help_text="API gravity of produced oil"
                    ),
                ),
                (
                    "gas_specific_gravity",
                    models.FloatField(
                        default=0.65, help_text="Gas specific gravity (air=1.0)"
                    ),
                ),
                (
                    "water_salinity",
                    models.FloatField(
                        default=20000.0, help_text="Water salinity (ppm)"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=180.0, help_text="Reservoir temperature (°F)"
                    ),
                ),
                (
                    "tubing_diameter",
                    models.FloatField(
                        default=2.875, help_text="Tubing inside diameter (inches)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pvt_properties",
                        to="analysis.analysissession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("well_id", models.CharField(max_length=255)),
                (
                    "mandrel_depths",
                    models.JSONField(
                        default=list, help_text="List of mandrel depths (ft)"
                    ),
                ),
                (
                    "packer_depth",
                    models.FloatField(
                        blank=True, help_text="Packer depth (ft)", null=True
                    ),
                ),
                (
                    "tubing_od",
                    models.FloatField(
                        blank=True,
                        help_text="Tubing outside diameter (inch)",
                        null=True,
                    ),
                ),
                (
                    "tubing_id",
                    models.FloatField(
                        blank=True, help_text="Tubing inside diameter (inch)", null=True
                    ),
                ),
                (
                    "injection_pressure_required",
                    models.FloatField(
                        blank=True,
                        help_text="Min surface pressure to reach mandrel (psi)",
                        null=True,
                    ),
                ),
                (
                    "feasibility_flag",
                    models.CharField(
                        choices=[
                            ("feasible", "Feasible"),
                            ("requires_deepening", "Requires Tubing Deepening"),
                            ("pressure_limited", "Insufficient Injection Pressure"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_data",
                        to="analysis.analysissession",
                    ),
                ),
            ],
        ),
    ]
