# Generated by Django 4.2.7 on 2026-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_welltrendanalysis_actual_glr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisweights",
            name="gas_constraint_mmscf",
            field=models.FloatField(
                blank=True,
                help_text="Available lift gas (MMscf/d) for knapsack optimization",
                null=True,
            ),
        ),
    ]
