# Generated by Django 4.2.17 on 2026-07-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_analysisweights_gas_constraint_mmscf"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisweights",
            name="base_choke_size",
            field=models.CharField(
                blank=True, help_text="Base choke size for normalization", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="analysisweights",
            name="outlier_method",
            field=models.CharField(
                default="iqr", help_text="Outlier detection method", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="analysisweights",
            name="outlier_threshold",
            field=models.FloatField(
                default=1.5, help_text="Outlier detection threshold"
            ),
        ),
    ]
