# Generated by Django 4.2.7 on 2026-07-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_analysisweights_base_choke_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="selected_wells",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of well IDs selected for analysis. Empty means all wells.",
            ),
        ),
    ]
