# Generated by Django 4.2.7 on 2026-07-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0007_analysissession_selected_wells"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welltrendanalysis",
            name="rejected_indices",
            field=models.JSONField(
                blank=True, default=dict, help_text="Indices of rejected outlier points"
            ),
        ),
    ]
